# Generated by Django 4.1.6 on 2023-05-17 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_remove_adminstrator_user_roles_delete_user_role_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline_Companie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Countrie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('countries', django_countries.fields.CountryField(max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField(null=True)),
                ('landing_time', models.DateTimeField(null=True)),
                ('number_tickets', models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)])),
                ('airline_company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airline_company', to='company_airline.airline_companie')),
                ('destination_country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='destination', to='company_airline.countrie')),
                ('origin_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_airline.countrie')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer', to='accounts.customer')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_airline.flight')),
            ],
        ),
        migrations.AddField(
            model_name='airline_companie',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_airline.countrie'),
        ),
    ]
