# Generated by Django 4.1 on 2022-12-12 16:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('company_airline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='airline_companie',
            old_name='country_id',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='destination_country_id',
            new_name='destination_country',
        ),
        migrations.RenameField(
            model_name='flight',
            old_name='origin_country_id',
            new_name='origin_country',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='customer_id',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='flight_id',
            new_name='flight',
        ),
        migrations.RemoveField(
            model_name='countrie',
            name='name',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='airline_company_id',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='remaining_tickets',
        ),
        migrations.AddField(
            model_name='countrie',
            name='countries',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='flight',
            name='airline_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airline_company', to='company_airline.airline_companie'),
        ),
        migrations.AddField(
            model_name='flight',
            name='number_tickets',
            field=models.IntegerField(default=1, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(200)]),
        ),
        migrations.AlterField(
            model_name='flight',
            name='departure_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='flight',
            name='landing_time',
            field=models.DateTimeField(null=True),
        ),
    ]
