# Generated by Django 4.1 on 2023-01-02 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('company_airline', '0003_alter_flight_airline_company_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='airline_company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='airline_company', to='company_airline.airline_companie'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company_airline.countrie'),
        ),
    ]
